/*
 * WireMock
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.26.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Body8;
import io.swagger.client.model.Body9;
import io.swagger.client.model.InlineResponse2002;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NearMissesApi
 */
@Ignore
public class NearMissesApiTest {

    private final NearMissesApi api = new NearMissesApi();

    /**
     * Find near misses matching request pattern
     *
     * Find at most 3 near misses for closest logged requests to the specified request pattern
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminNearMissesRequestPatternPostTest() throws ApiException {
        Body9 body = null;
        InlineResponse2002 response = api.adminNearMissesRequestPatternPost(body);

        // TODO: test validations
    }
    /**
     * Find near misses matching specific request
     *
     * Find at most 3 near misses for closest stub mappings to the specified request
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminNearMissesRequestPostTest() throws ApiException {
        Body8 body = null;
        InlineResponse2002 response = api.adminNearMissesRequestPost(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Retrieve near-misses for all unmatched requests
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminRequestsUnmatchedNearMissesGetTest() throws ApiException {
        InlineResponse2002 response = api.adminRequestsUnmatchedNearMissesGet();

        // TODO: test validations
    }
}
