/*
 * WireMock
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.26.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Body10;
import io.swagger.client.model.Body11;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse2003;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RecordingsApi
 */
@Ignore
public class RecordingsApiTest {

    private final RecordingsApi api = new RecordingsApi();

    /**
     * Take a snapshot recording
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminRecordingsSnapshotPostTest() throws ApiException {
        Body11 body = null;
        InlineResponse200 response = api.adminRecordingsSnapshotPost(body);

        // TODO: test validations
    }
    /**
     * Start recording
     *
     * Begin recording stub mappings
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminRecordingsStartPostTest() throws ApiException {
        Body10 body = null;
        api.adminRecordingsStartPost(body);

        // TODO: test validations
    }
    /**
     * Get recording status
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminRecordingsStatusGetTest() throws ApiException {
        InlineResponse2003 response = api.adminRecordingsStatusGet();

        // TODO: test validations
    }
    /**
     * Stop recording
     *
     * End recording of stub mappings
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminRecordingsStopPostTest() throws ApiException {
        InlineResponse200 response = api.adminRecordingsStopPost();

        // TODO: test validations
    }
}
