/*
 * WireMock
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.26.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse2004;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ScenariosApi
 */
@Ignore
public class ScenariosApiTest {

    private final ScenariosApi api = new ScenariosApi();

    /**
     * Get all scenarios
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminScenariosGetTest() throws ApiException {
        InlineResponse2004 response = api.adminScenariosGet();

        // TODO: test validations
    }
    /**
     * Reset the state of all scenarios
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminScenariosResetPostTest() throws ApiException {
        api.adminScenariosResetPost();

        // TODO: test validations
    }
}
