/*
 * WireMock
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.26.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Body;
import io.swagger.client.model.Body1;
import io.swagger.client.model.Body2;
import io.swagger.client.model.Body3;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse201;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StubMappingsApi
 */
@Ignore
public class StubMappingsApiTest {

    private final StubMappingsApi api = new StubMappingsApi();

    /**
     * Delete all stub mappings
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminMappingsDeleteTest() throws ApiException {
        api.adminMappingsDelete();

        // TODO: test validations
    }
    /**
     * 
     *
     * Find stubs by matching on their metadata
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminMappingsFindByMetadataPostTest() throws ApiException {
        Body2 body = null;
        InlineResponse200 response = api.adminMappingsFindByMetadataPost(body);

        // TODO: test validations
    }
    /**
     * Get all stub mappings
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminMappingsGetTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        InlineResponse200 response = api.adminMappingsGet(limit, offset);

        // TODO: test validations
    }
    /**
     * Create a new stub mapping
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminMappingsPostTest() throws ApiException {
        Body body = null;
        InlineResponse201 response = api.adminMappingsPost(body);

        // TODO: test validations
    }
    /**
     * Delete stub mappings matching metadata
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminMappingsRemoveByMetadataPostTest() throws ApiException {
        Body3 body = null;
        api.adminMappingsRemoveByMetadataPost(body);

        // TODO: test validations
    }
    /**
     * Reset stub mappings
     *
     * Restores stub mappings to the defaults defined back in the backing store
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminMappingsResetPostTest() throws ApiException {
        api.adminMappingsResetPost();

        // TODO: test validations
    }
    /**
     * Persist stub mappings
     *
     * Save all persistent stub mappings to the backing store
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminMappingsSavePostTest() throws ApiException {
        api.adminMappingsSavePost();

        // TODO: test validations
    }
    /**
     * Delete a stub mapping
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminMappingsStubMappingIdDeleteTest() throws ApiException {
        String stubMappingId = null;
        api.adminMappingsStubMappingIdDelete(stubMappingId);

        // TODO: test validations
    }
    /**
     * Get stub mapping by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminMappingsStubMappingIdGetTest() throws ApiException {
        String stubMappingId = null;
        InlineResponse201 response = api.adminMappingsStubMappingIdGet(stubMappingId);

        // TODO: test validations
    }
    /**
     * Update a stub mapping
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminMappingsStubMappingIdPutTest() throws ApiException {
        String stubMappingId = null;
        Body1 body = null;
        InlineResponse201 response = api.adminMappingsStubMappingIdPut(stubMappingId, body);

        // TODO: test validations
    }
}
