/*
 * WireMock
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.26.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Body12;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SystemApi
 */
@Ignore
public class SystemApiTest {

    private final SystemApi api = new SystemApi();

    /**
     * Reset mappings and request journal
     *
     * Reset mappings to the default state and reset the request journal
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminResetPostTest() throws ApiException {
        api.adminResetPost();

        // TODO: test validations
    }
    /**
     * Update global settings
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminSettingsPostTest() throws ApiException {
        Body12 body = null;
        api.adminSettingsPost(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Shutdown the WireMock server
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminShutdownPostTest() throws ApiException {
        api.adminShutdownPost();

        // TODO: test validations
    }
}
